# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: GitAction Demo

on:
  push:
    branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

jobs:
  mybuild:
    runs-on: ubuntu-latest

    #strategy:
      #matrix:
        #node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: 162.250.126.211
          user: git-action-user
          password: GitActions@01
          local_dir: "./ghactions"
          delete: "false"
